sequenceDiagram
participant przeglądarka
participant serwer
przeglądarka-->>serwer:GET https://studies.cs.helsinki.fi/exampleapp/spa
    serwer->>przeglądarka:przegladarka otrzymuje html z serwera
przeglądarka-->>serwer:GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    serwer->>przeglądarka:przegladarka otrzymuje js z serwera
przeglądarka-->>serwer:GET https://studies.cs.helsinki.fi/exampleapp/main.css
    serwer->>przeglądarka:przegladarka otrzymuje css z serwera
    note left of serwer:js pobiera dane notatek z serwera, 
    note left of serwer:przegladarka tworzy nowy kod html za pomoca dom-api dla poprawnego wyswietlania notatek bez przeladowania strony
    przeglądarka->>serwer:przegladarka przesyla dane do serwera przez formularz żądaniem POST uzytego przez JS
    przeglądarka-->>serwer:nowa notatka jest tymczasowo przechowywana w lokalnej tablicy ktora dopiero pozniej jest przesylana do serwera - aby zapobiec reloadowi strony
    serwer->>przeglądarka:kod 201 utworzono
    przeglądarka->>serwer:notatka jest wysylana z serwera do przegladarki przez funkcję notes.push(note)
    Note right of przeglądarka:strona NIE jest przeladowywana ponownie
