sequenceDiagram
    participant przeglądarka
    participant serwer

    Note right of przeglądarka: Użytkownik wpisuje treść i klika guzik Zapisz
    przeglądarka->>serwer: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    Note left of serwer: Serwer procesuje zapytanie i udostępnia je do pliku
    serwer-->>przeglądarka: Odpowiedź 302 do adresu https://studies.cs.helsinki.fi/exampleapp/notes
    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/notes
    serwer-->>przeglądarka: przeglądarka otrzymuje plik notes.html
    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    serwer-->>przeglądarka: przeglądarka otrzymuje plik css
    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    serwer-->>przeglądarka: przeglądarka otrzymuje plik JS
    Note right of przeglądarka: JS pobiera zaktualizowany plik https://studies.cs.helsinki.fi/exampleapp/notes
    serwer-->>przeglądarka:przeglądarka otrzymuje nowy plik notes.html
    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    serwer-->>przeglądarka: JSON ma nową notatkę i ją wyświetla
